package:
  name: clang
  version: 19.1.7

source:
  - git_url: https://github.com/llvm/llvm-project.git
    git_rev: llvmorg-19.1.7
    folder: llvm-project

requirements:
  # tools only required at build time
  build:
    - cmake
    - ninja
    - git
  # packages that need to be cross compatible, so linked depending on platform
  # so basically everything that we link against
  host:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - janniklasb::llvm==19.1.7
  # packages that should be installed with this package,
  # entries here might be duplicated from above if needed
  run:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - janniklasb::llvm==19.1.7