package:
  name: adaptivecpp
  version: 25.10.0

source:
  - git_url: https://github.com/AdaptiveCpp/AdaptiveCpp.git
    git_rev: v25.10.0
    folder: adaptivecpp

requirements:
  # tools only required at build time
  build:
    - cmake
    - ninja
    - git
  # packages that need to be cross compatible, so linked depending on platform
  # so basically everything that we link against
  host:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - janniklasb::llvm==19.1.7
    - janniklasb::clang==19.1.7
    - janniklasb::lld==19.1.7
    - cuda
    - rocm-smi
    - rocm-device-libs
    - rocm-opencl-runtime
    - intel-opencl-rt
  # packages that should be installed with this package,
  # entries here might be duplicated from above if needed
  run:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - janniklasb::llvm==19.1.7
    - janniklasb::clang==19.1.7
    - janniklasb::lld==19.1.7
    - cuda
    - rocm-smi
    - rocm-device-libs
    - rocm-opencl-runtime
    - intel-opencl-rt
    
test:
  files:
    - TestFiles/
  requires:
    - cmake
    - ninja
    - compilers