package:
  name: binder
  version: v1.4.5

source:
  - git_url: https://github.com/JanNiklasB/binder.git
    git_rev: binder_crpropa
    folder: binder

build:
  script_env:
    - ADDPATH  # [osx]

requirements:
  build:
  - coreutils  # [osx]
  - xz  # [osx]
  - pybind11  # [osx]
  - git  # [osx]
  - cmake  # [osx]
  - ninja  # [osx]

  run:
  # - coreutils  # [osx]
  # - xz  # [osx]
  - cmake
  - ninja
  - {{ compiler('c') }}
  - {{ compiler('cxx') }}
  - clang==19.1.7  # [linux]
  - clangxx==19.1.7  # [linux]
  - llvm==19.1.7  # [linux]
  - clang==14.0.6  # [osx]
  - clangxx==14.0.6  # [osx]
  - llvm==14.0.6  # [osx]
  - pybind11>3

test:
  files:
    - testProject/
  commands:
    - binder --help
    - binder --version

about:
  home: https://github.com/JanNiklasB/CRPropa_Pybind11_Bindings
  license_file: binder/LICENSE
  license_url: https://github.com/JanNiklasB/binder/blob/binder_crpropa/LICENSE
  summary: Fork of https://github.com/RosettaCommons/binder
  description: |
    This package is a custom version of [`RosettaCommons/binder`](https://github.com/RosettaCommons/binder) Version 1.4.3.
    It includes some needed bugfixes and adjustments needed for the python bindings of [`CRPropa`](https://github.com/CRPropa/CRPropa3)
    over [`JanNiklasB/CRPropa_Pybind11_Bindings`](https://github.com/JanNiklasB/CRPropa_Pybind11_Bindings) .
    It should work (and has in the past) also for other projects.
    This package also includes a cmake module (cppbinder) with enables simple integration of binder bindings in existing projects
    (see [`JanNiklasB/CRPropa_Pybind11_Bindings`](https://github.com/JanNiklasB/CRPropa_Pybind11_Bindings) for a detailed usage info).
  dev_url: https://github.com/RosettaCommons/binder
  doc_url: https://github.com/JanNiklasB/CRPropa_Pybind11_Bindings
  doc_source_url: https://github.com/JanNiklasB/CRPropa_Pybind11_Bindings/README.md