package:
  name: binder
  version: v1.4.3

source:
  - git_url: https://github.com/JanNiklasB/binder.git
    git_rev: binder_crpropa
    folder: binder

requirements:
  build:
  - clang==19.1.7 # [osx]
  - clangxx==19.1.7 # [osx]
  - llvm==19.1.7 # [osx]

  run:
  - {{ compiler('c') }}
  - {{ compiler('cxx') }}
  - clang==19.1.7
  - clangxx==19.1.7
  - llvm==19.1.7
  - pybind11

test:
  commands:
    - binder --help
    - binder --version
