name: binder_conda_package
on:
#   push:
#     branches: 
#       - master
#       - releases/**
#     paths:
#       - ".github/workflows/binder_conda_package.yml"
#       - "**.cpp"
#       - "**.h"
#       - "**.py"
#       - "**.i"
#       - "**/CMakeLists.txt"
#       - "conda-build/*"
#   release:
#     types: [published]
  workflow_dispatch:
  

jobs:
  build_package:
    strategy:
      matrix:
        os: [ubuntu-22.04, ubuntu-22.04-arm, macos-14]
    name: ${{ matrix.os }}_conda_package
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
      - name: Conda environment creation and activation
        uses: conda-incubator/setup-miniconda@v4.0.1
        with:
          python-version: 3.13
          auto-update-conda: false
          auto-activate-base: true
      - name: Install conda build
        run: conda install conda-build anaconda-client -y &> /dev/null
      - name: Build and upload conda package
        uses: uibcdf/action-build-and-upload-conda-packages@v1.5.0
        with:
          meta_yaml_dir: binder
          user: ${{ secrets.ANACONDA_ACCOUNTNAME }}
          token: ${{ secrets.ANACONDA_TOKEN }}
          overwrite: true
          conda_build_args: "-c conda-forge"