name: binder_conda_package
on:
#   push:
#     branches: 
#       - master
#       - releases/**
#     paths:
#       - ".github/workflows/binder_conda_package.yml"
#       - "**.cpp"
#       - "**.h"
#       - "**.py"
#       - "**.i"
#       - "**/CMakeLists.txt"
#       - "conda-build/*"
#   release:
#     types: [published]
  workflow_dispatch:
  

jobs:
  arm:
    runs-on: ubuntu-22.04-arm
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
      - name: Build and upload conda package
        uses: uibcdf/action-build-and-upload-conda-packages@v1.5.0
        with:
          meta_yaml_dir: binder/meta.yaml
          user: ${{ secrets.ANACONDA_ACCOUNTNAME }}
          token: ${{ secrets.ANACONDA_TOKEN }}
          overwrite: true
          conda_build_args: "-c conda-forge"

  x64:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
      - name: Build and upload conda package
        uses: uibcdf/action-build-and-upload-conda-packages@v1.5.0
        with:
          meta_yaml_dir: binder/meta.yaml
          user: ${{ secrets.ANACONDA_ACCOUNTNAME }}
          token: ${{ secrets.ANACONDA_TOKEN }}
          overwrite: true
          conda_build_args: "-c conda-forge"

  macos:
    runs-on: macos-14
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
      - name: Build and upload conda package
        uses: uibcdf/action-build-and-upload-conda-packages@v1.5.0
        with:
          meta_yaml_dir: binder/meta.yaml
          user: ${{ secrets.ANACONDA_ACCOUNTNAME }}
          token: ${{ secrets.ANACONDA_TOKEN }}
          overwrite: true
          conda_build_args: "-c conda-forge"